import docx
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os
from PIL import Image

def build_manuscript(md_file, image_file, output_file):
    doc = docx.Document()
    
    # Set default style
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Times New Roman'
    font.size = Pt(12)

    # 1. Parse Markdown
    if os.path.exists(md_file):
        with open(md_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                
                if line.startswith('### '):
                    h = doc.add_heading(line[4:], level=3)
                elif line.startswith('## '):
                    h = doc.add_heading(line[3:], level=2)
                elif line.startswith('# '):
                    h = doc.add_heading(line[2:], level=1)
                else:
                    p = doc.add_paragraph(line)
                    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    else:
        print(f"Error: {md_file} not found.")

    # 2. Add Figure
    if os.path.exists(image_file):
        doc.add_page_break()
        h = doc.add_heading("Figures", level=1)
        
        # Convert PNG to TIFF if requested or just use PNG (docx supports PNG well)
        # The user requested .tiff and .md to .docx
        tiff_file = image_file.replace('.png', '.tiff')
        try:
            with Image.open(image_file) as img:
                img.save(tiff_file, format='TIFF', compression='tiff_lzw')
            
            doc.add_picture(tiff_file, width=Inches(6.0))
            caption = doc.add_paragraph("Figure 1: Conceptual structure of plant-PM interaction pathways, highlighting physical capture kinetics and biochemical resilience markers.")
            caption.alignment = WD_ALIGN_PARAGRAPH.CENTER
            print(f"Added figure from {tiff_file}")
        except Exception as e:
            print(f"Failed to process image: {e}")
            # Fallback to PNG
            doc.add_picture(image_file, width=Inches(6.0))
    else:
        print(f"Error: {image_file} not found.")

    # 3. Save
    doc.save(output_file)
    print(f"Manuscript compiled successfully: {output_file}")

if __name__ == "__main__":
    # Use absolute paths or CWD
    BASE_DIR = os.getcwd()
    MD_PATH = os.path.join(BASE_DIR, "manuscript.md")
    # Image generated by generate_image is typically in the brain/ dir, 
    # but the user might expect it in the workspace. I'll use the path from the previous tool.
    # Note: I need the absolute path of the generated image.
    IMG_PATH = r"C:\Users\SOURISH SENAPATI\.gemini\antigravity\brain\cfaa98d6-e23a-4b11-9e12-7c3fabf3e867\biomonitoring_structure_diagram_1773048111110.png"
    OUTPUT_PATH = os.path.join(BASE_DIR, "PM_Biomonitoring_Review_Interim.docx")
    
    build_manuscript(MD_PATH, IMG_PATH, OUTPUT_PATH)
